[project]
name = "studio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepeval>=3.5.9",
    "google>=3.0.0",
    "reflex>=0.8.13",
]
